package cdb.dal.model;

import java.util.Date;

public class Anomalyinfo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column anomalyinfo.id
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column anomalyinfo.x
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private Integer x;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column anomalyinfo.y
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private Integer y;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column anomalyinfo.date
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private Date date;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column anomalyinfo.rId
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private Integer rid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column anomalyinfo.desc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private String desc;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column anomalyinfo.id
     *
     * @return the value of anomalyinfo.id
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column anomalyinfo.id
     *
     * @param id the value for anomalyinfo.id
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column anomalyinfo.x
     *
     * @return the value of anomalyinfo.x
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column anomalyinfo.x
     *
     * @param x the value for anomalyinfo.x
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column anomalyinfo.y
     *
     * @return the value of anomalyinfo.y
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column anomalyinfo.y
     *
     * @param y the value for anomalyinfo.y
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column anomalyinfo.date
     *
     * @return the value of anomalyinfo.date
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column anomalyinfo.date
     *
     * @param date the value for anomalyinfo.date
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column anomalyinfo.rId
     *
     * @return the value of anomalyinfo.rId
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column anomalyinfo.rId
     *
     * @param rid the value for anomalyinfo.rId
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column anomalyinfo.desc
     *
     * @return the value of anomalyinfo.desc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column anomalyinfo.desc
     *
     * @param desc the value for anomalyinfo.desc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }
}