package cdb.dal.model;

public class MaskDescBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maskdesc.id
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maskdesc.x
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    private Integer x;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maskdesc.y
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    private Integer y;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maskdesc.lat
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    private Double lat;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maskdesc.lon
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    private Double lon;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column maskdesc.catogory
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    private Integer category;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maskdesc.id
     *
     * @return the value of maskdesc.id
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maskdesc.id
     *
     * @param id the value for maskdesc.id
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maskdesc.x
     *
     * @return the value of maskdesc.x
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maskdesc.x
     *
     * @param x the value for maskdesc.x
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maskdesc.y
     *
     * @return the value of maskdesc.y
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maskdesc.y
     *
     * @param y the value for maskdesc.y
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maskdesc.lat
     *
     * @return the value of maskdesc.lat
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maskdesc.lat
     *
     * @param lat the value for maskdesc.lat
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maskdesc.lon
     *
     * @return the value of maskdesc.lon
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public Double getLon() {
        return lon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maskdesc.lon
     *
     * @param lon the value for maskdesc.lon
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public void setLon(Double lon) {
        this.lon = lon;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column maskdesc.catogory
     *
     * @return the value of maskdesc.catogory
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column maskdesc.catogory
     *
     * @param catogory the value for maskdesc.catogory
     *
     * @ibatorgenerated Thu Nov 12 15:23:31 MST 2015
     */
    public void setCategory(Integer category) {
        this.category = category;
    }
}