package cdb.dal.model;

public class Regiondesc {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regiondesc.id
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regiondesc.rWidth
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private Integer rwidth;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column regiondesc.rHeight
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private Integer rheight;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regiondesc.id
     *
     * @return the value of regiondesc.id
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regiondesc.id
     *
     * @param id the value for regiondesc.id
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regiondesc.rWidth
     *
     * @return the value of regiondesc.rWidth
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Integer getRwidth() {
        return rwidth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regiondesc.rWidth
     *
     * @param rwidth the value for regiondesc.rWidth
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setRwidth(Integer rwidth) {
        this.rwidth = rwidth;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column regiondesc.rHeight
     *
     * @return the value of regiondesc.rHeight
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Integer getRheight() {
        return rheight;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column regiondesc.rHeight
     *
     * @param rheight the value for regiondesc.rHeight
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void setRheight(Integer rheight) {
        this.rheight = rheight;
    }
}