package cdb.dal.dao;

import cdb.dal.model.Anomalyinfo;
import java.sql.SQLException;

public interface AnomalyinfoDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    void insert(Anomalyinfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    void insertSelective(Anomalyinfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    Anomalyinfo selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    int updateByPrimaryKeySelective(Anomalyinfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Anomalyinfo record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    int updateByPrimaryKeyWithoutBLOBs(Anomalyinfo record) throws SQLException;
}