package cdb.dal.dao;

import cdb.dal.model.Anomalyinfo;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;

public class AnomalyinfoDAOImpl implements AnomalyinfoDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public AnomalyinfoDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        Anomalyinfo key = new Anomalyinfo();
        key.setId(id);
        int rows = sqlMapClient.delete("anomalyinfo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void insert(Anomalyinfo record) throws SQLException {
        sqlMapClient.insert("anomalyinfo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public void insertSelective(Anomalyinfo record) throws SQLException {
        sqlMapClient.insert("anomalyinfo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public Anomalyinfo selectByPrimaryKey(Integer id) throws SQLException {
        Anomalyinfo key = new Anomalyinfo();
        key.setId(id);
        Anomalyinfo record = (Anomalyinfo) sqlMapClient
            .queryForObject("anomalyinfo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public int updateByPrimaryKeySelective(Anomalyinfo record) throws SQLException {
        int rows = sqlMapClient.update("anomalyinfo.ibatorgenerated_updateByPrimaryKeySelective",
            record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public int updateByPrimaryKeyWithBLOBs(Anomalyinfo record) throws SQLException {
        int rows = sqlMapClient.update("anomalyinfo.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
            record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table anomalyinfo
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    public int updateByPrimaryKeyWithoutBLOBs(Anomalyinfo record) throws SQLException {
        int rows = sqlMapClient.update("anomalyinfo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

}