package cdb.dal.dao;

import cdb.dal.model.MaskDescBean;
import java.sql.SQLException;
import java.util.List;

public interface MaskDescDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    void insert(MaskDescBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    void insertSelective(MaskDescBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    void insertSelectiveArr(List<MaskDescBean> records) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    MaskDescBean selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    int updateByPrimaryKeySelective(MaskDescBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    int updateByPrimaryKey(MaskDescBean record) throws SQLException;
}