package cdb.dal.dao;

import cdb.dal.model.MaskDescBean;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;

public class MaskDescDAOImpl implements MaskDescDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    public MaskDescDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    public int deleteByPrimaryKey(Integer id) throws SQLException {
        MaskDescBean key = new MaskDescBean();
        key.setId(id);
        int rows = sqlMapClient.delete("maskdesc.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    public void insert(MaskDescBean record) throws SQLException {
        sqlMapClient.insert("maskdesc.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    public void insertSelective(MaskDescBean record) throws SQLException {
        sqlMapClient.insert("maskdesc.ibatorgenerated_insertSelective", record);
    }

    /** 
     * @see cdb.dal.dao.MaskDescDAO#insertSelectiveArr(java.util.List)
     */
    @Override
    public void insertSelectiveArr(List<MaskDescBean> records) throws SQLException {
        sqlMapClient.insert("maskdesc.ibatorgenerated_insertSelectiveArr", records);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    public MaskDescBean selectByPrimaryKey(Integer id) throws SQLException {
        MaskDescBean key = new MaskDescBean();
        key.setId(id);
        MaskDescBean record = (MaskDescBean) sqlMapClient
            .queryForObject("maskdesc.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    public int updateByPrimaryKeySelective(MaskDescBean record) throws SQLException {
        int rows = sqlMapClient.update("maskdesc.ibatorgenerated_updateByPrimaryKeySelective",
            record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table maskdesc
     *
     * @ibatorgenerated Thu Nov 12 15:04:20 MST 2015
     */
    public int updateByPrimaryKey(MaskDescBean record) throws SQLException {
        int rows = sqlMapClient.update("maskdesc.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

}