package cdb.dal.dao;

import cdb.dal.model.RegionDescBean;
import java.sql.SQLException;

public interface RegionDescDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table regiondesc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    int deleteByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table regiondesc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    void insert(RegionDescBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table regiondesc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    void insertSelective(RegionDescBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table regiondesc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    RegionDescBean selectByPrimaryKey(Integer id) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table regiondesc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    int updateByPrimaryKeySelective(RegionDescBean record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table regiondesc
     *
     * @ibatorgenerated Thu Nov 05 16:46:02 MST 2015
     */
    int updateByPrimaryKey(RegionDescBean record) throws SQLException;
}